= Combination-Generation Static Library

[cols="<,>" frame=none, grid=none]
|===
|xref:C-API.adoc[< C-API]
|xref:Cpp-API.adoc[CPP-API >]
|===

== Description

The Combination-Generation library is used to generate:

* Combinations from a given set.

* A node sequence.

* A cyclic node sequence

== Examples:

* A combination given the number of elements in a list
    
    Given: Red, Green, Blue, Purple, Yellow, Pink
    Output: Blue, Purple, Yellow
    
* A combination with a given number of minimum elements from a list
    
    Given: Red, Green, Blue, Purple, Yellow, Pink
    Minimum: 3 elements
    Output: Red, Blue, Purple, Yellow
    
* A combination that must contain the elements passed in.
    
    Given: Red, Green, Blue, Purple, Yellow, Pink
    Included Elements: Red, Green, Pink
    Output: Red, Green, Blue, Purple, Pink

* Sequence generation: Given a start node choose a random element from a list of next nodes and repeat the process recursively until no node is available.

    Speak
        Guild Master
            Kill
                Goblin
                Orc
                Wolf
            Defend
                Town
        Merchant
            Retrieve
                Stolen Gold
                Amulet of Resistance
        Smith
            Craft
                Sword
                Dagger
                Axe
            Give
                10 Logs
                5 Gold Ingot
    Sequence: Speak -> Merchant -> Retrieve -> Stolen Gold
    Quest Speak to Merchant and retrieve the stolen gold

* Cyclic Node Sequence: Given a start node and a count choose a random element from a list of next nodes and repeat the process recursively until the sequence length reaches the count.

[NOTE]
 Cycles are allowed within next nodes list. A node can be available in its list of next nodes. A child node can have its parent as a next node

    Red
        Red
        Green
        Blue
        Yellow
    Green
        Red
        Green
        Blue
        Yellow
    Blue
        Red
        Green
        Blue
        Yellow    
    Yellow
        Red
        Green
        Blue
        Yellow    

    Sequence: Red -> Green -> Yellow -> Green -> Green -> Green -> Blue

== Dependencies

- Math
- Utility
