= Combination-Generation Static Library

[cols="<,>" frame=none, grid=none]
|===
|xref:C-API.adoc[< C-API]
|xref:Cpp-API.adoc[CPP-API >]
|===

== Description

The Combination-Generation library is used to generate:

* Combinations from a given set.

* A node sequence.

== Examples:

* A combination given the number of elements in a list
    
    Given: Red, Green, Blue, Purple, Yellow, Pink
    Output: Blue, Purple, Yellow
    
* A combination with a given number of minimum elements from a list
    
    Given: Red, Green, Blue, Purple, Yellow, Pink
    Minimum: 3 elements
    Output: Red, Blue, Purple, Yellow
    
* A combination that must contain the elements passed in.
    
    Given: Red, Green, Blue, Purple, Yellow, Pink
    Included Elements: Red, Green, Pink
    Output: Red, Green, Blue, Purple, Pink

* Sequence generation: Given a start node choose a random element from a list of next nodes and repeat the process recursively until node is available.

    Speak
        Guildmaster
            Kill
                Goblin
                Orc
                Wolf
            Defend
                Town
        Merchant
            Retrieve
                Stolen Gold
                Amulet of Resistance
        Smith
            Craft
                Sword
                Dagger
                Axe
            Give
                10 Logs
                5 Gold Ingot
    Sequence: Speak -> Merchant -> Retrieve -> Stolen Gold
    Quest Speak to Merchant and retrieve the stolen gold

== Dependencies

- Math
- Utility
